### ISSUE TITLE
ModuleNotFoundError: No module named 'decoding_algorithm.contrastive_decoding'

### ISSUE THREAD

**Issue by pkulium** [yfqiu-nlp/sea-llm#2]
Traceback (most recent call last):
  File ".//src/benchmark_evaluation/bbq_eval.py", line 28, in <module>
    from decoding_algorithm import Inference
  File "/sea-llm/src/decoding_algorithm/__init__.py", line 1, in <module>
    from .contrastive_decoding import ContrastiveDecoding
ModuleNotFoundError: No module named 'decoding_algorithm.contrastive_decoding'

**Comment by yfqiu98** [comment]
Hi, thanks for the issue. I see you have posted a similar issue before. To solve both, you just need to add the ./src path into your the sys.path.

**Comment by pkulium** [comment]
Hello! I search the package, there is no function or class definition for ContrastiveDecoding in all files. 

In src/decoding_algorithm/__init__.py, '''from .contrastive_decoding import ContrastiveDecoding''' but the file is missing

**Comment by yfqiu98** [comment]
Oh sorry for that. I have fix the issue now, please pull and try again.
